### PR TITLE
Extending support for django 1.10 and DRF 3.4 and 3.5

### PR DESCRIPTION
**Pull request by ydaniv**

### CODE REVIEW

**Comment by auvipy** [comment]
all builds are failing!

**Comment by ydaniv** [comment]
Yes, this is work in progress, and not going very well. I think I'll drop it for now and focus on #21

**Comment by fmarco** [comment]
@ydaniv any update on this one? I'm very interested on drf 3.5 support :+1:

**Comment by ydaniv** [comment]
hey @fmarco! been pretty busy lately, new kid, new product, now on vacation (:
Unless I could get some help, maybe I can get back to it during mid-late March.

**Comment by fmarco** [comment]
@ydaniv Hi, thanks for your answer!
I think this app is a very nice, useful and cool project that can help devs on drf api projects a lot!
I'd like to use this in production if only drf3.5 was covered :)!
Maybe in the future i'll contribute if you need some help.
Take your time.

**Comment by fmarco** [comment]
ps: in some cases seems failing because of drf and dj incompatibility

**Comment by yprez** [comment]
@ydaniv , I'm currently trying to fix support for Django 1.11...

what do you think about dropping older Django versions (1.6, 1.7 at least) and 2.x versions of DRF?

**Comment by auvipy** [comment]
i think they should be removed

**Comment by ydaniv** [comment]
I think you're right, it's about time we do, and older versions are still available.

**Comment by ydaniv** [comment]
closed via #25

**Pull request closed without merging**
