### PR TITLE
Test on Django 1.10, 1.11, DRF 3.4, 3.5, 3.6, Python 3.6

### PR DESCRIPTION
**Pull request by yprez**

### CODE REVIEW

**Comment by ydaniv** [comment]
❤️ !!!

**Comment by ydaniv** [comment]
ok, from what I understand it's all good, besides the fact that Travis don't have a py3.6 interpreter, right?

So in that case, we can remove 3.6 for now and merge.

WDYT?

**Comment by ydaniv** [comment]
No, should be supported since end of last year. 

Perhaps specifying Python versions explicitly like [here](https://docs.travis-ci.com/user/languages/python/) will do the job?

**Comment by yprez** [comment]
Fixed :D

**Comment by ydaniv** [comment]
much obliged!

**Pull request merged**
