### PR TITLE
Make pagination field configurable

### LINKED ISSUE #8: Remove `List` test's hard-coded assumption of pagination turned on
The test now looks for `'resutls'` inside `response.data` and this needs to be configurable.

### PR DESCRIPTION
**Pull request by yprez**
Made the pagination "results" field configurable in `ListAPITestCaseMixin`.
Fixes #8 

Still needs:
1. Tests - the current tests pass, but I don't know how to easily test renamed result fields, or no fields at all. Need to create another viewset for this.
2. Documentation.

@ydaniv , can you review? If it's good I can try adding tests / docs.

### CODE REVIEW

**Comment by ydaniv** [comment]
Thanks @yprez ! I'll reveiw now!

**Comment by ydaniv** [comment]
Hey! Sorry for the delay, looks just about right.

I'll add docs and tests and merge it. Thanks!

**Comment by yprez** [comment]
@ydaniv what do you think is the best way to solve this?

a. To add docs + tests to this PR then merge
b. Try guessing the pagination class from the view
c. Something else?

**Comment by ydaniv** [comment]
Hey @yprez! Thanks for kicking my behind about this :+1: 
We need to think how to both allow configuring this for pre DRF 3.2 and for +3.2 where the API for pagination changed completely.

Do you have any idea how to approach this?

**Comment by yprez** [comment]
No idea (yet)... I'll take a look at the pagination changes and try to come up with something

**Pull request merged**
