### PR TITLE
Fix setup error py2.7

### PR DESCRIPTION
**Pull request by ydaniv**

### CODE REVIEW

**Comment by dnna2610** [comment]
Hi. Thank you for noticing and fixing this error. Can you please tag a release for it?

**Comment by ydaniv** [comment]
I have: `0.2.3`, is there anything else I'm missing?

**Comment by dnna2610** [comment]
If my reading is correct. When comparing 0.2.3 to 0.2.2, the try catch to fix 2.7 encoding error is not included in 0.2.3, only the "fix long description" commit is included.

**Comment by dnna2610** [comment]
0.2.3 is tagged on commit: [34b53df](https://github.com/ydaniv/django-rest-assured/commit/34b53df494ef9df2733533f327e7d424b20eb089) and not the expected [22c86f0](https://github.com/ydaniv/django-rest-assured/commit/22c86f0bcf9cbc12c6ea0d334776074a0fa993bc).

**Comment by ydaniv** [comment]
Yes, missed the tag on git, but the correct dist is published to pypi. Besides, this commit only fixes the long description for pypi readme.
Is this somehow blocking you on installing on py2.7?

**Pull request merged**
