### PR TITLE
Use tox-travis for better integration between tox and travis.ci

### PR DESCRIPTION
**Pull request by yprez**

### CODE REVIEW

**Comment by ydaniv** [comment]
🌟 🎉 🌟  Thanks! 🌟 🎉 🌟 

Just checking, you sure about that version matrix? cause I think DRF 3.0-3.2 support Django 1.6-1.8.

**Comment by yprez** [comment]
Pretty sure, I just removed those tests that were failing. Their envs were skipped in .travis.yml before (e.g. there is no line for `py27-django1.6-drf3.2` in the removed diff.

My guess is that no one has run `tox -e` locally before (it would take a veeery long time with all those envs), so no one knew they were failing...

Maybe some of those are supported and failing for a different reason, or maybe I need to do another split between Django 1.6, 1.7 to cover everything...

**Comment by yprez** [comment]
I think that everything is covered now

**Comment by ydaniv** [comment]
Thanks! 👍

**Pull request merged**
