### PR TITLE
Support for url params

### PR DESCRIPTION
**Pull request by maccesch**
new class parameter `reverse_args`

Also added tests of course

### CODE REVIEW

**Comment by maccesch** [comment]
Travis tells me about some contenttypes problems for Django versions < 1.8
That's strange because I didn't add or change any database/model stuff.
Any hints on how to resolve this?

**Comment by ydaniv** [comment]
Firstly, thanks for your work!

Now, trying to review the idea. Could you explain your use-case? I can't see the reason for adding arguments to a `list`/`create` endpoint, or to add extra arguments to an `update` endpoint.

**Comment by maccesch** [comment]
Yes, of course. I have an API that can CRUD objects belonging to a logged in user (endpoint /object/...). But if the user is an admin he also has access to other user's objects (endpoint /object/from-user/{user-id}/...)

**Comment by ydaniv** [comment]
OK then, if I'm not mistaken, for starters, you should be doing
```python
[object_id] + self.reverse_arguments
```
And not the other way around, right?

**Comment by maccesch** [comment]
No that is actually the correct order because a detail route will look like `/object/from-user/{user_id}/{pk-of-object}/`

**Comment by ydaniv** [comment]
Sounds like a very specific use-case. Can you convince me that a generic addition to the library is essential here?

Why not simply override `get_list_url()`/`get_detail_url()`/`get_create_url()`/get_update_url()`/`get_destroy_url()`?
If we add `reverse_args` why not also add `reverse_kwargs`?

On a side note, I've just recently [closed a similar PR to Tornado](https://github.com/tornadoweb/tornado/pull/1508) from the same reasons (:

**Comment by maccesch** [comment]
I added this feature because it seemed to me to be a feature that you'd need now and then and to require overriding all these methods just for that seemed excessive :D

True, kwargs would make sense too. If you want I implement it.

Anyway, even if not everyone needs it, it doesn't hurt to have it, right? The option is there if needed and there is virtually no perfomance impact.

**Comment by ydaniv** [comment]
I'm not worried at all about performance. Mostly about cruft.

I'll be OK with adding something similar, but since this addition is not even addressing the most general case, since one may want to add the `object_id` at the beginning and another at the front.

If you come up with a solution that's clean and is more generic I'd consider adding it.

I think for now, the best option for someone with your use case is to declare a mixin like:

```python
class ReverseArgsAPITestCaseMixin(object):

    def get_list_url(self):
        ...

    def get_detail_url(self):
        ...

    def get_create_url(self):
        ...

    def get_update_url(self):
        ...

    def get_delete_url(self):
        ...
```

You write it once and mix with any test case that needs this override.

WDYT?

**Comment by maccesch** [comment]
Yes I understand your reasoning. You're right, I guess that would be the best solution at the moment.

**Pull request closed without merging**
