### PR TITLE
Tests refactored

### PR DESCRIPTION
**Pull request by eracle**
Hello there! I hope everything is fine.
I am PRing this branch with some re-factorings before I can propose an additional functionality, I will post it in the future.
In this branch I have separated the tests that relies on mocks in the 'mocking' package (inside tests), and the all the test app related in the app package. By doing so I could have replaced the mocked factories with real factory_boy's factories. 
My next steps are:
- add some additional tests that do not relies on mocks;
- propose a new functionality.

Thanks in advance.
Regards

### CODE REVIEW

**Comment by eracle** [comment]
Hi, it seems that Travis tries to load django 2.0 with python 2.7.
By the way Django doesn't support python 2 anymore. https://docs.djangoproject.com/en/2.0/releases/2.0/#python-compatibility

**Comment by eracle** [comment]
I've fixed some stuff, let's see if Travis crashes now.

**Comment by ydaniv** [comment]
Thanks @eracle .

I'm having a few concerns:

1. I'd like factory_boy to not be a dependency of DRA.
2. You have removed the flake8 test completely. We need to have a lint test.

If you could address these, I can continue with a more thorough review.

**Comment by eracle** [comment]
Dear Yanv, I understand your concerns about not having factory_boy as a dependency.
Unfortunately, the aim of this PR was to expressly include it, in order to test DRA library against factory_boy's behavior. By the way, I understand that the issued direction could not be shared among developers. And I accept it. I will have a look on some literacy on writing portable libraries and their best practices, then I will make you know further. Anyway the PR's direction is that one, so if it is not shared, I accept the refuse response.
Thanks for your time.
Regards

**Comment by eracle** [comment]
Hello there! What's up?
I'v meditated over the issued problem, and I figured out the following solution:
Why don't we use a separate requirement files for production and development?
It is a built-in feature in node.js: by using the 'devDependencies' vs 'dependencies' in the package.json file.
[This](https://medium.com/@alonisser/things-i-wish-pip-learned-from-npm-f712fa26f5bc) blog post mentions it.
If appears to be the right solution I can go through it during the next week or the following one.
Regards

**Comment by eracle** [comment]
Is this project dead? @ydaniv

**Pull request closed without merging**
